[global.databases]
typify = { url = "typify.sqlite" }

[development]
address = "localhost"
port = 8000
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
#log = "normal"
#limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
#limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
#limits = { forms = 32768 }