[global.databases]
typify = { url = "typify.sqlite" }

[development]
address = "localhost"
port = 8000
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
tls = { key = "openssl/server.crt", certs = "openssl/server.crt" }
#log = "normal"
#limits = { forms = 32768 }

[staging]
address = "localhost"
port = 80
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
#limits = { forms = 32768 }

[production]
address = "localhost"
port = 443
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
tls = { key = "openssl/server.crt", certs = "openssl/server.crt" }
#limits = { forms = 32768 }