[global.databases]
typify = { url = "typify.sqlite" }

[development]
address = "localhost"
port = 8000
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
secret_key = "E19fSEJwDP/PlL+mD6Zz87p/IU7+DY20ipEJFrOsysM="
#log = "normal"
#limits = { forms = 32768 }

[production]
address = "localhost"
port = 80
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "E19fSEJwDP/PlL+mD6Zz87p/IU7+DY20ipEJFrOsysM="
#tls = { key = "openssl/server.key", certs = "openssl/server.crt" }
#limits = { forms = 32768 }